sonar.projectKey=python-web-app
sonar.projectName=Python Web Application
sonar.projectVersion=1.0
sonar.sources=.
sonar.exclusions=**/node_modules/**, **/backend/__pycache__/**, **/frontend/__pycache__/**, **/Dockerfile, **/.git/**
sonar.language=py
sonar.python.version=3.11
sonar.sourceEncoding=UTF-8
sonar.tests=backend/tests,frontend/tests
